# Generated by Django 3.0.4 on 2020-03-31 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200330_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='media',
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 10, 11, 51, 282022)),
        ),
    ]
