# Generated by Django 3.0.4 on 2020-03-31 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200331_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 10, 12, 38, 730239)),
        ),
    ]
