# Generated by Django 3.0.4 on 2020-03-31 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20200331_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 13, 21, 7, 959822)),
        ),
    ]
