# Generated by Django 3.0.4 on 2020-03-24 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i2', to='accounts.Interest')),
                ('interest_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i3', to='accounts.Interest')),
                ('interest_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i4', to='accounts.Interest')),
                ('primary_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
