# Generated by Django 3.0.4 on 2020-03-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
