# Generated by Django 3.0.4 on 2020-03-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
        ('accounts', '0002_interest_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='TV_Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=50)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('studio', models.CharField(max_length=50)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Genre')),
            ],
        ),
    ]
