# Generated by Django 3.0.4 on 2020-03-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interest_4',
        ),
    ]
