# Generated by Django 3.0.4 on 2020-03-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_interest_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_game',
            name='platform',
        ),
    ]
