# Generated by Django 3.0.4 on 2020-03-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
        ('accounts', '0006_remove_video_game_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=60, null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Genre')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Interest')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='tv_show',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='video_game',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='TV_Show',
        ),
        migrations.DeleteModel(
            name='Video_game',
        ),
    ]
