# Generated by Django 3.0.4 on 2020-03-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200326_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
