# Generated by Django 3.0.4 on 2020-03-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200331_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
