# Generated by Django 3.0.4 on 2020-03-12 10:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='film_app.Director'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(default=datetime.date(2020, 3, 12)),
        ),
    ]
